### ISSUE TITLE
一个计算错误

### ISSUE THREAD

**Issue by frankfoot** [frankfoot/HyperCalculation#2]
> -1*-382931093+899543875*3+(378219)-6
 Ans:-378225

正确答案应为3081940931

简化版:
>(378)-6
Ans:301

**Comment by problem233** [comment]
![jkhy w1uqp _n8n4w rz_b0](https://user-images.githubusercontent.com/13145126/27477794-d0aeb2ca-583f-11e7-9fa5-9d54241cdc4f.jpg)

**Comment by frankfoot** [comment]
Fixed a few days ago.
